### ISSUE TITLE
DomainEventItem promises closed unions that publishSystemEvent's rows fall outside of

### ISSUE THREAD

**Issue by JamesNeumann** [hb-dragons/dragons-hub#154]
Found while doing #151. It is the reason 3 of that ticket's 23 casts were deliberately left in place: they are not signature widening, they are an assertion the data contradicts.

## The contradiction

`DomainEventItem` declares:

```ts
type: EventType;              // EVENT_TYPES
entityType: EventEntityType;  // ["match", "booking", "referee", "task"]
```

But `publishSystemEvent` (`apps/api/src/services/events/event-publisher.ts:149`) writes rows that satisfy neither:

- `type: "admin.test_push"` — `SystemEventType`, declared at `event-publisher.ts:118` and **deliberately** outside `EVENT_TYPES`. The comment at `:111` says so explicitly. Written by `services/notifications/test-push.service.ts:152`.
- `entityType: "user"` — not one of the four `EVENT_ENTITY_TYPES`, because a system event is about an account action rather than a tracked entity.

`listDomainEvents` returns those rows through `DomainEventItem`. So in `event-admin.service.ts`:

```ts
r.type as DomainEventListResult["events"][number]["type"]
r.entityType as DomainEventListResult["events"][number]["entityType"]
```

is laundering in the real sense — the type claims a closed union that live rows are known to fall outside of.

## Why it matters

Any consumer that switches exhaustively on `DomainEventItem["type"]` is wrong today, and TypeScript will tell it the switch is exhaustive when it is not. The same applies to `entityType`. A `default:` branch is currently load-bearing without anyone having decided that.

This is not hypothetical: system events are written on every admin test-push, so these rows exist in the events list in production.

## The decision

This is a **response-contract** change, not a refactor, which is why #151 left it alone:

1. **Widen the response type** to `EventType | SystemEventType` and add `"user"` to the entity union (or a separate `SystemEventEntityType`). Honest about what the endpoint returns. Forces every consumer to handle the extra members — which is the point, but it is a breaking type change for `apps/web`.
2. **Exclude system events from the listing.** Filter `listDomainEvents` to rows whose type is in `EVENT_TYPES`. Keeps the union closed and the type honest, but silently hides rows an admin might expect to see in an event browser — and the admin event browser is exactly where you would look to confirm a test push fired.
3. **Split the response.** A discriminated union with a `kind: "domain" | "system"` tag. Most precise, most work, and probably over-engineered for one extra event type.

Option 1 is the likely answer, but it needs a look at what `apps/web`'s event browser does with `type` before committing — including the i18n key lookup, which the #75 sweep already found was rendering a non-existent event type to admins.

## Acceptance criteria

- [ ] Decision recorded on which option
- [ ] The 3 remaining casts in `event-admin.service.ts` are gone, not suppressed
- [ ] Web's event browser handles whatever the new union admits, including its i18n keys
- [ ] A test asserts that a row written by `publishSystemEvent` round-trips through `listDomainEvents` with its real type intact

Part of #44. Sibling of #152, which covers the `jsonb` payload of the same table.

**Comment by JamesNeumann** [comment]
Fixed in 8db610a7 — **option 1 (widen the response type)**, landed together with
#155 (see below for why they could not be separated).

## The check the issue asked for first

Before committing to the widening I looked at what `apps/web` does with `type`,
including the i18n lookup the #75 sweep flagged. It is safe:

- The table renders `{event.type}` **raw** — there is no per-type i18n key at
  all, so there is no missing-key risk.
- `entityTypeLabel()` and `sourceLabel()` already end in `default: return <raw>`.

So widening the union breaks nothing in web's rendering. That removed the main
argument for options 2 and 3.

## What landed

`@dragons/shared` gains `SYSTEM_EVENT_TYPES` / `SYSTEM_EVENT_ENTITY_TYPES` and
the `StoredEventType` / `StoredEventEntityType` unions they combine into.
`DomainEventItem.type` / `.entityType` now use the stored unions.

The split the original comment was protecting is preserved and now explicit:
`EVENT_TYPE_VALUES` and `EVENT_ENTITY_TYPES` remain the **publishable**
vocabulary that `triggerEventSchema` and watch rules validate against, so an
admin still cannot create or subscribe to `admin.test_push`. Only the read side
widened. `SystemEventType` moved out of `event-publisher.ts` into shared
because the response type has to name it.

**The 3 casts are gone, not suppressed.** `domain_events.type`, `.source` and
`.entity_type` carry `.$type<>()` in the Drizzle schema — the honest place for
the narrowing, since the column really does hold those values. `db:generate`
confirms `No schema changes, nothing to migrate`.

## Acceptance criteria

- [x] Decision recorded (option 1)
- [x] The 3 casts in `event-admin.service.ts` are gone
- [x] Web handles the new union, i18n included — `entityTypes.user` added to
      `en`/`de`, and the entityType filter now offers `user`
- [x] A test asserts a `publishSystemEvent` row round-trips through
      `listDomainEvents` with its real type intact

That round-trip test passes at runtime either way — the defect was in the
*declared* type — so it is paired with a compile-time guard asserting
`DomainEventItem["type"]` admits `"admin.test_push"`. That guard is what
actually failed first:

```
event-admin.service.test.ts(190,11): error TS2322: Type '"admin.test_push"' is not assignable to type 'EventType'.
event-admin.service.test.ts(191,11): error TS2322: Type '"user"' is not assignable to type '"match" | "referee" | "task" | "booking"'.
```

## Two findings along the way

1. **`health.routes.test.ts` and `test-push.service.test.ts` seeded
   `type: "match.updated"` — not a real event type.** The typed column caught
   both; they now seed `match.created`. `match.updated` and `match.scheduled`
   still appear as fixture strings in `digest.worker.test.ts`,
   `swr-queries.test.ts` and `contracts/src/notification.test.ts`, which do not
   go through the typed column. Left alone as out of scope — worth a follow-up.
2. **The enum-column drift guard was mapping `domain_events.type` /
   `entity_type` to the publishable arrays**, which was wrong for the same
   reason this issue exists. Repointed at the stored arrays; the publishable
   ones are now in `NOT_PERSISTED` with their reason. `domain_events.source`
   joined the guard for the first time, since #155 gave `EventSource` a const
   array to be guarded against.

## Why it shipped with #155

The compiler forced it. Typing the column is what lets the casts go; a typed
column is what makes `eq(domainEvents.type, someBareString)` in
`listDomainEvents` stop compiling, which is #155. Split into two commits,
neither half builds on its own.

Gates on the merge commit: lint 0 errors (baseline api 17 / native 15 / web 5,
unchanged), typecheck 9/9, `pnpm test` 9/9, `pnpm coverage` 9/9 within
thresholds, knip, i18n, ai-slop, skipped-test, design-token checks all pass.
